### ISSUE TITLE
KeyError: 'formats' - (youtube_extract-script.py", line 11)

### ISSUE THREAD

**Issue by namaljayathunga** [dbeley/youtube_extract#14]
Thanks for the scripts. I'm getting this error every time.

youtube_extract https://www.youtube.com/channel/UCKf4vzRQJc9cVfaAYaZBS1w -e csv

Traceback (most recent call last):
  File "D:\Programs\Python\Python38-32\Scripts\youtube_extract-script.py", line 11, in <module>
    load_entry_point('youtube-extract==1.3.6', 'console_scripts', 'youtube_extract')()
  File "d:\programs\python\python38-32\lib\site-packages\youtube_extract-1.3.6-py3.8.egg\youtube_extract\__main__.py", line 85, in main
  File "d:\programs\python\python38-32\lib\site-packages\youtube_extract-1.3.6-py3.8.egg\youtube_extract\__main__.py", line 50, in extract_entries_for_url
KeyError: 'formats'

**Comment by dbeley** [comment]
Hello! I have updated the script, can you confirm it's fixed on your side with the latest version?
